LP-12:component Header
VasiliPodoplielov/learning-platform pull request #12
Opened 2024-04-04 18:34 UTC by MaksymPi

2024-04-04 18:38 UTC, VasiliPodoplielov requested changes

2024-04-04 18:38 UTC, VasiliPodoplielov commented on src/components/Header/Header.tsx
> +    const items: MenuItem[] = menuItems;
Навіщо це? Ти можеш одразу використовувати речі експортовані з іншиї файлів.

2024-04-04 18:38 UTC, VasiliPodoplielov commented on src/components/Header/Header.tsx
> +        const headerActions = (
Повторюю вдруге - неправильне форматування.

2024-04-05 06:00 UTC, VasiliPodoplielov requested changes

2024-04-05 06:00 UTC, VasiliPodoplielov commented on src/components/Header/Header.tsx
> +        <div className='header'>
Цей дів тут взагалі не треба. Просто повертай  MenuBar.

2024-04-05 06:00 UTC, VasiliPodoplielov commented on src/components/Header/Header.tsx
> +            <Menubar className='text-xl'  model={menuItems} start={logo} end={headerActions} />
Нащо клас text-xl?

2024-04-05 07:51 UTC, MaksymPi commented on src/components/Header/Header.tsx
> +            <Menubar className='text-xl'  model={menuItems} start={logo} end={headerActions} />
Збільшив розмір шрифту, на великому розширенні маленький шрифт.

2024-04-05 08:14 UTC, VasiliPodoplielov approved these changes

2024-04-05 08:14 UTC, merged