language functionality
VasiliPodoplielov/learning-platform pull request #17
Opened 2024-04-12 19:06 UTC by MaksymPi

2024-04-17 07:06 UTC, VasiliPodoplielov requested changes

2024-04-17 07:06 UTC, VasiliPodoplielov commented on .husky/pre-push
> +npm run lint -- --fix
Проблема по стороні твого вс коду. перевірив у себе в вскод - усе працює нормально.

2024-04-17 07:06 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/LanguageSwitcher.tsx
> +import { countryOptionTemplate } from './Template';
Чому Template з великої літери? Це має бути просто у хелпер вайлі.

2024-04-17 07:06 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/LanguageSwitcher.tsx
> +        optionLabel="name"
Для чого використовується цей проп?

2024-04-17 07:06 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/Template.tsx
> +      src="https://primefaces.org/cdn/primereact/images/flag/flag_placeholder.png"
Урл перемістити в константу і покласти в правильний файл.

2024-04-17 07:06 UTC, VasiliPodoplielov commented on src/components/SiteInfo/SiteInfo.tsx
Чому коміти і зміни з SiteInfo роблять у цьому пулреквесті?

2024-04-17 07:06 UTC, VasiliPodoplielov commented on .husky/pre-commit
> +npm run lint -- --fix
Те саме що і нижче.

2024-04-17 10:14 UTC, VasiliPodoplielov requested changes

2024-04-17 10:14 UTC, VasiliPodoplielov commented on .eslintrc.json
> +    "plugin:prettier/recommended"
Нащо змінив?

2024-04-17 10:14 UTC, VasiliPodoplielov commented on .prettierrc
> +  "printWidth": 80,
Те саме питання що і вище

2024-04-17 10:14 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/constants.ts
> +export const Countries = ['UA', 'PL', 'DE', 'EN'];
ти ж сам написав що константи пишемо капсом

2024-04-17 10:28 UTC, MaksymPi commented on .eslintrc.json
> +    "plugin:prettier/recommended"
Коли робив настройки прітера по білду з інтернета.

2024-04-17 10:29 UTC, MaksymPi commented on .prettierrc
> +  "printWidth": 80,
Щоб строка не розтягувалась дуже, як ти казав

2024-04-17 10:39 UTC, VasiliPodoplielov requested changes

2024-04-17 10:39 UTC, VasiliPodoplielov commented on .eslintrc.json
> +    "plugin:prettier/recommended"
Видаляй.

2024-04-17 10:39 UTC, VasiliPodoplielov commented on src/components/Header/constants.ts
> +export const GET_MENU_ITEMS = (getTranslation: (key: string) => string) => [
Це константа?

2024-04-17 10:39 UTC, VasiliPodoplielov commented on src/components/Header/constants.ts
Файл краще перейменувати на dataHelpers.ts

2024-04-17 10:40 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/constants.ts
> +export const COUNTIES = ['UA', 'PL', 'DE', 'EN'];
Помилка у назві

2024-04-18 06:15 UTC, VasiliPodoplielov requested changes

2024-04-18 06:15 UTC, VasiliPodoplielov commented on src/components/Header/dataHelpers.ts
> +export const GET_MENU_ITEMS = (getTranslation: (key: string) => string) => [
Це константа?

2024-04-18 06:15 UTC, VasiliPodoplielov commented on src/components/LanguageSwitcher/LanguageSwitcher.tsx
> +        optionLabel="name"
Питання все ще актуальне.

2024-04-18 10:26 UTC, VasiliPodoplielov approved these changes

2024-04-18 10:27 UTC, merged