Feature/lp 17 creation teachers section
VasiliPodoplielov/learning-platform pull request #18
Opened 2024-04-22 14:48 UTC by MaksymPi

2024-04-22 15:11 UTC, VasiliPodoplielov requested changes

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeachersSection.tsx
Мені не подобається назва TeacherSection. Чому не просто Teachers?

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/assets/images/teachers/user-female.png
Чому саме пнг формат? Не забувай що пнг більше займає місця і це означає що зображення довше буде завантажуватися.

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeacherCard.tsx
> +export const TeacherCard = ({ teacher }: { teacher: Teacher }) => {
Тип неправильно. створи файл types.ts і туди додай інтерфейс Teacher, а тут використай інтерфейс Props { teacher: Teacher }

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeacherCard.tsx
> +    <>
Нащо тут реакт фрагмент?

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeacherCard.tsx
> +        footer={footer}
Футер і хедер можна не виносити у змінні, можна прямо сюди додавати так як вони маленькі.

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeacherCard.tsx
> +export const TeacherCard = ({ teacher }: { teacher: Teacher }) => {
Через деструктуризацію можна одразу у змінні покласти поля, а не використовувати teacher.someField.

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeacherCard.tsx
> +    <div className="card flex justify-content-center">
Цей дів тут точно треба?

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/TeachersSection.tsx
> +  const { t } = useTranslation();
Форматування.

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/dataTeachers.ts
> +export const teachersData = (getTranslation: (key: string) => string) => [
Думай що тут не так.

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/dataTeachers.ts
> +      altText: 'Teachers Image',
Якщо у тебе всюди алтТекст однаковий, нащо це поле взагалі?

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/i18n/locales/de/translation.json
> +  "TeachersSection": {
чому з великої?

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/i18n/locales/ua/translation.json
> +      "cv": "Привіт! Мене звати Лара, я з Сіднея, Австралія. Моя пристрасть — подорожувати світом і знайомитися з новими культурами. Я люблю грати у футбол і проводити час з друзями та родиною."
Поле cv не збігається з тим що там написано. Якщо там опис викладача то окей, але зараз тут написане представлення викладача до майбутніх учнів. Якщо це так - то тоді поле щось типу introduction

2024-04-22 15:11 UTC, VasiliPodoplielov commented on src/components/TeachersSection/dataTeachers.ts
> +    id: '2',
id не мають повторюватися.

2024-04-23 09:33 UTC, MaksymPi commented on src/assets/images/teachers/user-female.png
Лінтер при іншому, шкаржиться

2024-04-23 09:58 UTC, MaksymPi commented on src/components/TeachersSection/dataTeachers.ts
> +export const teachersData = (getTranslation: (key: string) => string) => [
тут потрібна допомога)

2024-04-23 11:05 UTC, VasiliPodoplielov requested changes

2024-04-23 11:05 UTC, VasiliPodoplielov commented on src/components/Teachers/TeacherCard.tsx
> +export const TeacherCard = ({ teacher }: { teacher: Teacher }) => {
Тип для пропсів неправильний. я у попередньому коменті казав як зробити. + є дока

2024-04-23 11:05 UTC, VasiliPodoplielov commented on src/components/Teachers/TeacherCard.tsx
> +      title={teacher.name}
Зроби через деструктуризацію одразу з пропсів, щоб не використовувати teachers.fieldName

2024-04-23 11:05 UTC, VasiliPodoplielov commented on src/components/Teachers/carouselResponsiveOptions.ts
> +export const responsiveOptions = [
Я вже розказував як зберігати константи.

2024-04-23 11:05 UTC, VasiliPodoplielov commented on src/components/Teachers/types.ts
> +    altText: string;
це поле все ще треба?

2024-04-24 19:22 UTC, VasiliPodoplielov requested changes

2024-04-24 19:22 UTC, VasiliPodoplielov commented on src/components/Teachers/TeacherCard.tsx
> +  const { url: imageUrl } = image;
Чому ти це не можеш зробити одразу у рядку вище?

2024-04-24 19:22 UTC, VasiliPodoplielov commented on src/components/Teachers/TeacherCard.tsx
> +  const imageAltText = 'Teacher image';
Лишня змінна. Нащо вона? Вона використовується тільки один раз, тому немає сенсу її виносити в змінну.

2024-04-24 19:22 UTC, VasiliPodoplielov commented on src/components/Teachers/carouselResponsiveOptions.ts
Якщо у тебе буде ще 10 констант, для них ще 10 файлів створиш?

2024-04-24 19:22 UTC, VasiliPodoplielov commented on src/components/Teachers/types.ts
> +  image: {
То якщо у тебе тільки одне поле, нащо ця вкладеність?

2024-04-24 19:22 UTC, VasiliPodoplielov commented on src/components/Teachers/dataTeachers.ts
Вже є приклад як треба називати такі файли.

2024-04-24 20:18 UTC, VasiliPodoplielov approved these changes

2024-04-24 20:29 UTC, merged