LP:28 New desing header and SiteInfo
VasiliPodoplielov/learning-platform pull request #32
Opened 2024-08-28 16:37 UTC by MaksymPi

2024-08-28 20:49 UTC, VasiliPodoplielov requested changes

2024-08-28 20:49 UTC, VasiliPodoplielov commented on src/components/SiteInfo/SiteInfo.tsx
> +      <h1 className="custom-title-class pb-5">{t('siteInfoSection.titleInfo')}</h1>
Що це за клас? Я його не бачу у ПР. Якщо він все ж є - переробити назву, вона дуже загальна і ні про зо не каже

2024-08-28 20:49 UTC, VasiliPodoplielov commented on src/components/SiteInfo/SiteInfo.tsx
> +      className={`headerSection flex-column flex justify-content-center h-screen m-0 p-0 ${styles.bgHeaderCard}`}
Що за клас хедерСекшин?

2024-08-28 20:49 UTC, VasiliPodoplielov commented on src/components/SiteInfo/SiteInfo.tsx
> +  const customHeader = (
Коли додаєш якісь елементи для прайму як реактівські елементи то по правилам прайму треба використовувати наступну назву твояНазваЯкогосьЕлементуTemplate, наприклад cardHeaderTemplate.
Про це десь у доці треба шукати.

2024-08-28 20:49 UTC, VasiliPodoplielov commented on src/components/SiteInfo/SiteInfo.tsx
> +        style={{ background: 'transparent' }}
Треба використовувати один підхід, або через класи або через style. Почали через класи - так і роби далі. Створи якийсь файлік типу sharedStyles.module.css і туди складай спільні стилі/класи, типу bgTransparent і цей клас будеш використовувати де потрібно.

2024-08-29 08:15 UTC, MaksymPi commented on src/components/SiteInfo/SiteInfo.tsx
> +      className={`headerSection flex-column flex justify-content-center h-screen m-0 p-0 ${styles.bgHeaderCard}`}
Тестував, забув видалити)

2024-08-29 08:37 UTC, VasiliPodoplielov approved these changes

2024-08-29 08:38 UTC, merged